name: otlob
version: 1.0.0+1
description: A definitive light & soft food delivery UI Kit for Otlob.
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  flutter_bloc: ^8.1.3
  go_router: ^10.0.0
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  get_it: ^7.6.4
  equatable: ^2.0.5
  pdf: ^3.10.4
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.1.5
  location: ^5.0.3
  flutter_lints: ^6.0.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
