name: otlob
version: 1.0.0+1
description: A definitive light & soft food delivery UI Kit for Otlob.
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
platforms:
  android: true
  ios: true
  web: true
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  flutter_bloc: ^9.1.1
  go_router: ^16.2.4
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  get_it: ^8.2.0
  equatable: ^2.0.5
  pdf: ^3.10.4
  flutter_dotenv: ^6.0.0
  google_sign_in: 6.1.5
  google_sign_in_android: 6.2.1
  location: ^8.0.1
  flutter_lints: ^6.0.0
  bloc: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
